### PR TITLE
Allow custom tags for ECR docker image

### PR DESCRIPTION
**Pull request by gregbeech**
Currently the ECR docker image is only tagged with the SHA1 of the commit. However, we'd also like to be able to tag it with 'latest' so it's possible for people to pull the latest Identity container for local use. As we're using this helper script to push the container, we need to update it to allow additional tags to be passed in.

### CODE REVIEW

**Comment by marcinwyszynski** [comment]
I'd prefer that instead of allowing arbitrary tags, we restricted the list to a small number of whitelisted ones, so that we could tell Hopper to ignore those rather than try to pull non-existent commits from GitHub.

**Comment by gregbeech** [comment]
The only one I really care about is `latest`, and TBH can't really think of any other use-cases, so could implement it as a single switch `--tag-latest` maybe if you don't want to allow arbitrary tags?

**Comment by marcinwyszynski** [comment]
Actually, I suppose we could use a regex like `/[0-9a-f]{40}/`, so ✅

**Comment by gregbeech** [comment]
Just realised I missed a `;;` at the end of the case, so added it.

**Pull request merged**
