### PR TITLE
Use debian as the image base

### PR DESCRIPTION
**Pull request by bencord0**
Remove heroku scripts
 - Remove dependency on nodejs
 - We don't need to push to heroku now that we have hopper
(Only used by loris)

Install docker-ce from the official docker repository (don't pin the version)
Pin the signing key in this repository.

Remove the extra need to install gnu versions of tar/gzip and other helpers

Bump the version of this image to 0.2.0

### CODE REVIEW

**Comment by bencord0** [comment]
https://circleci.com/gh/deliveroo/orderweb/40308

Looks like it works

**Comment by bencord0** [comment]
@marcinwyszynski How long do you want to keep this as a side branch?
I'm happy to remove the `-pre` tag and merge to master as `0.2.0`.

**Comment by marcinwyszynski** [comment]
I think we're good now then @bencord0

**Comment by marcinwyszynski** [comment]
Would it warrant a `CHANGELOG` entry?

**Pull request merged**
